name: CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "api/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: docker/setup-buildx-action@master

      - uses: docker/login-action@master
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: docker/build-push-action@master
        with:
          push: true
          tags: ${{ env.REGISTRY_HOST }}/nexata/api:${{ contains(github.ref, 'main') && 'stable' || 'latest' }}
